apiVersion: v1

  kind: Pod

  metadata:
    name: simple-web-app
    labels:
      name: simple-web-app

  spec:
    containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 8080

      - name: log-agent
        image: log-agent

      - name: app
        image: kodekloud/event-simulator
        volumeMounts:
      - mountPath: /log
        name: log-volume

      - name: sidecar
        image: kodekloud/filebeat-configured
        volumeMounts:
        - mountPath: /var/log/event-simulator/
          name: log-volume

      volumes:
      - name: log-volume
        hostPath:
          # directory location on host
          path: /var/log/webapp
          # this field is optional
          type: DirectoryOrCreate