apiVersion: apps/v1

kind: Deployment

metadata:
  name: myapp-blue
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v1

    spec:
      containers:
        - name: app-container
          image: myapp-image:1.0

  replicas: 3
  selector:
    matchLabels:
      version: v1
