apiVersion: apps/v1

kind: Deployment

metadata:
  name: myapp-canary
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v1
        app: front-end

    spec:
      containers:
        - name: app-container
          image: myapp-image:2.0

  replicas: 1
  selector:
    matchLabels:
      app: front-end