apiVersion: v1

kind: Service

metadata:
  name: redis-service
  labels:
    name: redis-service
    type: demo-voting-app
  
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    type: demo-voting-app
    