apiVersion: v1

kind: Deployment

metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    type: demo-voting-app
  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      type: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        type: demo-voting-app
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
    