apiVersion: v1

kind: Service

metadata:
  name: db
  labels:
    name: postgres-pod
    type: demo-voting-app
  
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    type: demo-voting-app