apiVersion: v1

kind: Secret

metadata:
  name: app-secret

#secrets in plain text
data:
  DB_Host: mysql
  DB_User: root
  DB_Password: password

#displaying the secrets in plain text is not the recommended way
#lets encode these plain text - refer below line
#"echo -n 'mysql' | base64"
#view secrets - "kubectl get secrets" / "kubectl describe secrets"
#lets decode these plain text - refer below line
#"echo -n 'sgjk|*^' | base64 --decode"

#secrets in coded text
data:
  DB_Host: sgjk|*^
  DB_User: dqad&^
  DB_Password: wdqd12^($)