apiVersion: apps/v1

kind: ReplicationController

metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: fron-tend

    spec:
      containers:
        - name: nginx
          image: nginx

  replicas: 3
  selector:
    matchLabels:
      type: fron-tend